### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Berry-lc** [leo-frank/diff-gaussian-rasterization-depth#1]
I want to render the depth maps of gaussian model, how could I use this module?

**Comment by leo-frank** [comment]
Please refer to the [codes](https://github.com/graphdeco-inria/gaussian-splatting/blob/d9fad7b3450bf4bd29316315032d57157e23a515/gaussian_renderer/__init__.py#L85) from [original reference implementation of "3D Gaussian Splatting for Real-Time Radiance Field Rendering"](https://github.com/graphdeco-inria/gaussian-splatting), where the reference implementation only render the rgb image, like the following:
```
    rendered_image, radii = rasterizer(
        means3D = means3D,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity,
        scales = scales,
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)
```
To use our implementation, add two more variables (depth_map & weight_map) to receive rendered depth map and weight map:
```
    rendered_image, radii, depth_map, weight_map = rasterizer(
        means3D = means3D,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity,
        scales = scales,
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)

```

**Comment by Berry-lc** [comment]
I get it, thanks your so quick answer!
：）
