### ISSUE TITLE
How to Visualize Depth Map

### ISSUE THREAD

**Issue by Pumbaa-peng** [leo-frank/diff-gaussian-rasterization-depth#2]
I use the following code to save the depth map as an image:
**depth_map_pil = transforms.ToPILImage()(depth_map)**
Corresponding to the 3D-GS model predicted image and the real image are as follows：
<img width="476" alt="image" src="https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/77153588/48ec74c7-a3df-43bd-93f2-c14ff266bd85">
<img width="477" alt="image" src="https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/77153588/46022f6a-23c1-4fe1-acdc-d0c2c69fb2cb">
<img width="478" alt="image" src="https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/77153588/23190382-d443-459d-9ca0-431c4f78a56f">
<img width="477" alt="image" src="https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/77153588/b3a71647-e3d8-4855-82bc-c75ebf129b1e">
It doesn't seem to be working very well.

**Comment by leo-frank** [comment]
As you can see from the first figure(rendered image from 3D GS)  and the second figure(ground truth image), the rendering result is not realistic, which implies that the 3D GS have not converge perfectly on your dataset. That's the reason why the fourth figure(rendered depth) map is not accurate.

**Comment by leo-frank** [comment]
In terms of how to visualize depth map, please using the following codes:

```
import cv2
from PIL import Image
import torchvision.transforms as T
def apply_colormap(gray, minmax=None, cmap=cv2.COLORMAP_JET):
    """
    Input:
        gray: gray image, tensor/numpy, (H, W)
    Output:
        depth: (3, H, W), tensor
    """
    if type(gray) is not np.ndarray:
        gray = gray.detach().cpu().numpy().astype(np.float32)
    gray = gray.squeeze()
    assert len(gray.shape) == 2
    x = np.nan_to_num(gray)  # change nan to 0
    if minmax is None:
        mi = np.min(x)  # get minimum positive value
        ma = np.max(x)
    else:
        mi, ma = minmax
    x = (x - mi) / (ma - mi + 1e-8)  # normalize to 0~1
    x = (255 * x).astype(np.uint8)
    x_ = Image.fromarray(cv2.applyColorMap(x, cmap))
    x_ = T.ToTensor()(x_)  # (3, H, W)
    return x_

torchvision.utils.save_image(
    apply_colormap(rendered_depth),
    "depth_rendered_depth.png",
)

```

**Comment by Pumbaa-peng** [comment]
Thank you very much for your reply, I'll try to optimize my code, thanks again!
