### ISSUE TITLE
How to correctly blend depth by alpha?

### ISSUE THREAD

**Issue by flymin** [leo-frank/diff-gaussian-rasterization-depth#3]
Hi,

Thank you for sharing your implementation.
I notice in [this line](https://github.com/leo-frank/diff-gaussian-rasterization-depth/blob/03f0b7d00383d6e96c22b37325ac9e5450947bf5/cuda_rasterizer/forward.cu#L382) the depth is divided by the accumulated alpha. However, some other implementations do not have this operation, such as [here](https://github.com/ashawkey/diff-gaussian-rasterization/blob/d986da0d4cf2dfeb43b9a379b6e9fa0a7f3f7eea/cuda_rasterizer/forward.cu#L379) and [here](https://github.com/ingra14m/depth-diff-gaussian-rasterization/blob/2eb32ea251d3b339dab3af8b6fd78d7dec3caf8e/cuda_rasterizer/forward.cu#L377). I am new to this. Could you please shed some light on the reason for such differences?

Thank you in advance for your help.

Best,
flymin

**Comment by leo-frank** [comment]
Sorry for the late reply.

 In fact, we must do the-division-operation, as the sum of weights is not always approaching 1.
 
![image](https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/47302141/ab7d991e-0b6c-41eb-b659-2daad11a0c0c)
