### ISSUE TITLE
Depth scale

### ISSUE THREAD

**Issue by ProKaroly** [leo-frank/diff-gaussian-rasterization-depth#4]
First: Thank you very much for your excellent work!

Unfortunately, I am not an expert of this field. My goal is to extract ORB features from the gaussian splat model. I would like to use the 3D coordinate of the 2D image point. For this purpose I would like to get the Z depth for the detected keypoint. 

Can you help me to understand, that the depth_map from the rasteriztion is come back with z depth values can be matched with the pointcloud ( the input of the GSPLAT) ?
So basicaly the question is: how can I get back pixel’s pointcloud coordinate?

Thank you, in advance!

**Comment by leo-frank** [comment]
Yes, when we have the 2D coordinate and depth of the image-space key point, we can backproject to 3D space:

![image](https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/47302141/71b1187a-3eb6-46e6-9232-5c2b1c3a7411)

where R_c2w and t_c2w are the camera poses in camera-to-world convention, K is the intrinsic matrix and (x,y, depth) refer to the 2D coordinate and depth of the image-space key points

**Comment by Dumeowmeow** [comment]
> Yes, when we have the 2D coordinate and depth of the image-space key point, we can backproject to 3D space:
> 
> ![image](https://private-user-images.githubusercontent.com/47302141/342304782-71b1187a-3eb6-46e6-9232-5c2b1c3a7411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODQxMDYsIm5iZiI6MTcyOTY4MzgwNiwicGF0aCI6Ii80NzMwMjE0MS8zNDIzMDQ3ODItNzFiMTE4N2EtM2ViNi00NmU2LTkyMzItNWMyYjFjM2E3NDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDExNDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOGI4NzE0MmQxOWJiNGE0NmNhMjU5NWZkZGI5MjcxNjdhZTMzMjNlYjJkMmZlM2Q3M2FmMGM0ZjI3NjIwNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5AvSsfLfcUS2s8xP96ZnZOXIx3n7cFrWAPq_tmdmCfw)
> 
> where R_c2w and t_c2w are the camera poses in camera-to-world convention, K is the intrinsic matrix and (x,y, depth) refer to the 2D coordinate and depth of the image-space key points

Is the coordinate calculated in this way the world coordinate of the point cloud on the surface of the object？
