### ISSUE TITLE
Mathematical Supplement for the depth acquirement

### ISSUE THREAD

**Issue by YingjianYu** [leo-frank/diff-gaussian-rasterization-depth#5]
Thank you for your great work!
Could you please provide the mathematical supplement for the depth acquirement?

**Comment by leo-frank** [comment]
Sorry for late reply. 

Yeah, the depth is computed as 
![image](https://github.com/leo-frank/diff-gaussian-rasterization-depth/assets/47302141/df13f2da-0c8f-49e6-9571-0fb0ef4204ce)

where w_i is the weight of gaussian and d_i is the z-axis distance (e.g., depth) of the coordinate of gaussian
