### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by DavidLuBit** [leo-frank/diff-gaussian-rasterization-depth#6]
Hi~can you help me fix the following error:

cuda_rasterizer\rasterizer_impl.cu(201): error: declaration is incompatible with "int CudaRasterizer::Rasterizer::forward(std::function<char *(size_t)>, std::function<char *(size_t)>, std::function<char *(size_t)>, int, int, int, const float *, int, int, const float *, const float *, const float *, const float *, const float *, float, const float *, const float *, const float *, const float *, const float *, float, float, __nv_bool, float *, float *, int *, __nv_bool)"
D:\Programs\Endo-4DGS-main\Endo-4DGS-main\submodules\diff-gaussian-rasterization-depth\cuda_rasterizer\rasterizer.h(31): here.

**Comment by leo-frank** [comment]
I have recompiled this repo on a different machine. Other users also compile it successfully. So, it's not easy to determine the specific reason, an advice is to re-downloading and it may work.
