### ISSUE TITLE
Could you describe the process of the backward of depth map?

### ISSUE THREAD

**Issue by Zerui-Yu** [leo-frank/diff-gaussian-rasterization-depth#8]
Hi, thanks for the extention. But I have a question about it... In the process of depth map backwarding, the depth of the Gaussian kernel in alpha-blending-based depth map rendering is derived from the z-axis coordinate of the center of the Gaussian distribution. In fact, it is automatically optimized with μ in the original version of backpropagation. Is it really necessary to calculate its gradient during backwarding?

**Comment by leo-frank** [comment]
if you use the rendered depth as another optimization target besides vanilla photometric loss, then you must calculate the gradient from depth. A widely-used example is to supervise rendered depth with monocular depth from single-view depth estimation model in sparse-view settings.
